In [301]:
import numpy as np
import pandas as pd
from scipy import stats

In [302]:
rank_data=pd.read_csv('data.csv')
rank_data

Avg_Kills  Avg_Deaths  Avg_Assists  Avg_KDA  Avg_total_gold  \
0         9.92        4.15         7.31     8.25        12732.31   
1         4.15        4.85         6.50     3.20         9208.70   
2         6.50        9.00         8.50     1.66        12305.95   
3         6.70        5.95         6.55     3.58        11465.35   
4        10.25        7.90         6.15     2.36        12844.50   
..         ...         ...          ...      ...             ...   
866       7.60        6.85         8.35     2.55        11153.65   
867       6.45        6.00         8.00     3.58        11494.40   
868       5.90        5.65         5.90     2.70        10457.45   
869       7.50        4.90         8.00     3.71        11815.15   
870       5.00        5.90         7.30     3.16         9553.45   

     Avg_total_minion  Rank  
0              114.54     0  
1              131.40     0  
2              164.05     0  
3              152.70     0  
4              155.60     0  
..                ...   ...  
866             33.45     8  
867            172.30     8  
868            124.25     8  
869            182.20     8  
870            126.35     8  

[871 rows x 7 columns]

In [303]:
X=rank_data.iloc[:,:6]
y=rank_data.iloc[:,-1]

In [304]:
X=X.to_numpy()
y=y.to_numpy()

In [305]:
X=stats.zscore(X,axis=0)
X

array([[ 1.77340806e+00, -1.16769585e+00, -4.67191313e-01,
         3.74787662e+00,  1.06664324e+00, -9.80476997e-02],
       [-9.53197200e-01, -6.40275110e-01, -7.87133989e-01,
        -3.59034334e-01, -1.17590428e+00,  2.07366024e-01],
       [ 1.57291942e-01,  2.48657642e+00,  2.84792562e-03,
        -1.61143886e+00,  7.95292956e-01,  7.98810751e-01],
       ...,
       [-1.26237200e-01, -3.75085505e-02, -1.02412856e+00,
        -7.65659180e-01, -3.81156507e-01,  7.78459694e-02],
       [ 6.29840514e-01, -6.02602200e-01, -1.94647553e-01,
         5.57230100e-02,  4.82930826e-01,  1.12759243e+00],
       [-5.51530915e-01,  1.50855999e-01, -4.71141223e-01,
        -3.91564321e-01, -9.56493437e-01,  1.15886825e-01]])

In [306]:
muy_y = np.mean(y, axis=0)
muy_y

4.052812858783008

In [307]:
sigma_y = np.std(y, axis=0)
sigma_y

2.5932816601079227

In [308]:
y=stats.zscore(y,axis=0)
y

array([-1.56281245, -1.56281245, -1.56281245, -1.56281245, -1.56281245,
       -1.56281245, -1.56281245, -1.56281245, -1.56281245, -1.56281245,
       -1.56281245, -1.56281245, -1.56281245, -1.56281245, -1.56281245,
       -1.56281245, -1.56281245, -1.56281245, -1.56281245, -1.56281245,
       -1.56281245, -1.56281245, -1.56281245, -1.56281245, -1.56281245,
       -1.56281245, -1.56281245, -1.56281245, -1.56281245, -1.56281245,
       -1.56281245, -1.56281245, -1.56281245, -1.56281245, -1.56281245,
       -1.56281245, -1.56281245, -1.56281245, -1.56281245, -1.56281245,
       -1.56281245, -1.56281245, -1.56281245, -1.56281245, -1.56281245,
       -1.56281245, -1.56281245, -1.56281245, -1.56281245, -1.56281245,
       -1.56281245, -1.56281245, -1.56281245, -1.56281245, -1.56281245,
       -1.56281245, -1.56281245, -1.56281245, -1.56281245, -1.56281245,
       -1.56281245, -1.56281245, -1.56281245, -1.56281245, -1.56281245,
       -1.56281245, -1.56281245, -1.56281245, -1.56281245, -1.56

In [309]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,random_state=42,test_size=0.2)

In [310]:
X_train.shape,X_test.shape,y_train.shape,y_test.shape

((696, 6), (175, 6), (696,), (175,))

Denoted vecto theta=[theta1 theta2 ... thetaN] as W

First, I build a model that use a linear function

In [311]:
def calculate_y_hat(W,X,b):
    m=X.shape[0]
    y_hat=np.zeros(m)
    y_hat=np.dot(X,W)+b
    return y_hat

In [312]:
def calculate_loss_function(y_hat,y):
    m=y_hat.shape[0]
    loss=0
    for i in range(m):
        loss+=((y_hat[i]-y[i])**2)/m/2
    return loss

In [313]:
def calculate_gradient_vector(W,X,b,Y):
    m=X.shape[0]
    n=W.shape[0]
    dW=np.zeros(n)
    db=0
    y_hat=calculate_y_hat(W,X,b)
    for i in range(m):
        for j in range(n):
            dW[j]+=(y_hat[i]-Y[i])*X[i][j]/m
        db+=(y_hat[i]-Y[i])/m
    return dW,db

In [314]:
W=np.random.rand(*X.shape[1:])*0.01
b=np.random.rand()
loss=0

In [315]:
learning_rate=0.001
iterate_time=10000

In [316]:
for k in range(iterate_time):
    dW,db=calculate_gradient_vector(W,X,b,y)
    W-=learning_rate*dW
    b-=learning_rate*db
    y_hat=calculate_y_hat(W,X,b)
    loss=calculate_loss_function(y_hat,y)
    if (k+1)%10==0:
        print("Cost: ",loss)

Cost:  0.6137410501352235
Cost:  0.6079298337601079
Cost:  0.6022936174453638
Cost:  0.5968262377615953
Cost:  0.5915217801987951
Cost:  0.5863745680470278
Cost:  0.5813791518075806
Cost:  0.5765302991082347
Cost:  0.5718229850976719
Cost:  0.5672523832952517
Cost:  0.5628138568736473
Cost:  0.5585029503529494
Cost:  0.554315381685947
Cost:  0.550247034715297
Cost:  0.5462939519842898
Cost:  0.5424523278838511
Cost:  0.5387185021192745
Cost:  0.53508895348102
Cost:  0.531560293904729
Cost:  0.5281292628063037
Cost:  0.5247927216786713
Cost:  0.5215476489374697
Cost:  0.5183911350035831
Cost:  0.5153203776110211
Cost:  0.51233267732923
Cost:  0.5094254332894848
Cost:  0.5065961391055004
Cost:  0.5038423789789012
Cost:  0.5011618239806939
Cost:  0.49855222850024167
Cost:  0.4960114268537826
Cost:  0.493537330044808
Cost:  0.49112792266909616
Cost:  0.48878125995749067
Cost:  0.4864954649498818
Cost:  0.4842687257941886
Cost:  0.48209929316439876
Cost:  0.47998547779206496
Cost:  0.477925

In [317]:
y_pred_1=calculate_y_hat(W,X_test,b)
y_pred_1

array([-0.08708408, -0.49093116,  0.10657838, -0.18949968,  0.46115869,
        0.85682439, -1.37528862,  0.61264309, -0.31410661, -0.12488374,
        0.15463999,  0.2294319 , -0.18058041, -0.16739106,  0.43272986,
       -0.94781686, -0.57319613, -0.4265483 , -0.4749203 , -0.09232518,
       -0.28231685, -0.91556473,  0.16367532,  0.05302621,  0.16702295,
       -0.2637292 , -0.46447386, -0.09864897,  0.03352036,  0.05555622,
       -0.19646258, -0.10410115,  1.02101818,  0.34469404,  0.54094728,
       -0.18381239,  0.93475343, -0.20296886,  0.34759832,  0.25418799,
        0.08146583,  0.81075928,  0.11491698, -0.70031057, -0.58092469,
        0.10510425,  0.31327064,  0.21929535, -0.01032828,  0.13029021,
       -0.09698336, -0.05844981, -0.15106913,  0.69743008, -0.19655295,
        0.07848139,  0.35702276,  0.04702475,  0.14615207, -0.46702582,
        0.85521057, -0.44882326, -0.21690417,  0.18035386,  0.53320037,
        0.19454589,  0.34068801,  0.21183495, -0.97217933,  0.04

In [318]:
y_test

array([-0.02036526, -1.56281245,  0.36524654, -1.56281245,  1.52208192,
        1.13647013, -1.56281245,  1.52208192,  0.75085833, -0.02036526,
       -0.40597706, -0.02036526, -0.40597706, -0.40597706,  0.36524654,
       -0.79158885, -0.02036526,  1.52208192, -0.40597706,  0.36524654,
       -1.17720065, -0.40597706, -0.40597706,  0.36524654, -0.02036526,
       -0.40597706, -1.56281245, -1.56281245, -1.56281245,  1.52208192,
        1.13647013, -0.40597706,  1.13647013,  1.13647013,  1.52208192,
       -0.02036526,  1.13647013, -1.56281245,  0.75085833,  0.36524654,
        1.13647013,  1.13647013,  0.36524654, -1.56281245,  1.52208192,
       -0.40597706, -0.40597706,  0.36524654,  1.13647013,  1.52208192,
       -0.79158885,  1.52208192,  0.36524654,  0.75085833, -1.17720065,
        1.13647013,  0.75085833, -1.17720065,  0.36524654, -0.40597706,
        1.13647013, -1.56281245, -1.56281245,  1.13647013,  0.75085833,
        1.52208192, -0.40597706,  0.36524654, -0.40597706,  0.36

In [319]:
mse1=np.mean((y_test-y_pred_1)**2)
mse1
#y_hat_test=y_hat_test*sigma_y+muy_y
#y_hat_test
#y_test=y_test*sigma_y+muy_y
#y_test
#mse1=np.mean((y_test-y_hat_test)**2)
#mse1

0.736727723060169

In [320]:
W,W*sigma_y+muy_y

(array([ 0.05303123, -0.29529977, -0.10800433,  0.14461705, -0.23100135,
         0.04465646]),
 array([4.19033777, 3.28701738, 3.77272721, 4.42784559, 3.45376129,
        4.16861964]))

In [321]:
b,b-np.sum(W*muy_y/sigma_y)

(2.178927788118317e-05, 0.6126453890884366)

In [322]:
X,y

(array([[ 1.77340806e+00, -1.16769585e+00, -4.67191313e-01,
          3.74787662e+00,  1.06664324e+00, -9.80476997e-02],
        [-9.53197200e-01, -6.40275110e-01, -7.87133989e-01,
         -3.59034334e-01, -1.17590428e+00,  2.07366024e-01],
        [ 1.57291942e-01,  2.48657642e+00,  2.84792562e-03,
         -1.61143886e+00,  7.95292956e-01,  7.98810751e-01],
        ...,
        [-1.26237200e-01, -3.75085505e-02, -1.02412856e+00,
         -7.65659180e-01, -3.81156507e-01,  7.78459694e-02],
        [ 6.29840514e-01, -6.02602200e-01, -1.94647553e-01,
          5.57230100e-02,  4.82930826e-01,  1.12759243e+00],
        [-5.51530915e-01,  1.50855999e-01, -4.71141223e-01,
         -3.91564321e-01, -9.56493437e-01,  1.15886825e-01]]),
 array([-1.56281245, -1.56281245, -1.56281245, -1.56281245, -1.56281245,
        -1.56281245, -1.56281245, -1.56281245, -1.56281245, -1.56281245,
        -1.56281245, -1.56281245, -1.56281245, -1.56281245, -1.56281245,
        -1.56281245, -1.56281245, -1.562

Now we do the regression with a quadratic function, with theta equals to:

theta=(phiTphi)**(-1)*phiT*Y

In [323]:
X_design_2 = [np.ones(X.shape[0])]
for i in range(X.shape[1]):
    X_design_2.append(X[:, i])
for i in range(X.shape[1]):
    for j in range(i, X.shape[1]): 
        X_design_2.append(X[:, i] * X[:, j])
X_design_2 = np.column_stack(X_design_2)
X_transpose_2 = X_design_2.T
beta_2 = np.linalg.inv(X_transpose_2 @ X_design_2) @ X_transpose_2 @ y
y_pred_2 = X_design_2 @ beta_2
mse2 = np.mean((y - y_pred_2) ** 2)

print("Mean Squared Error:", mse2)

Mean Squared Error: 0.6001606673747402


Now we have 3-degree polynomial regression model

In [324]:
X_design_3 = [np.ones(X.shape[0])]
lambda_reg_3=1
for i in range(X.shape[1]):
    X_design_3.append(X[:, i])
for i in range(X.shape[1]):
    for j in range(i, X.shape[1]): 
        X_design_3.append(X[:, i] * X[:, j])
for i in range(X.shape[1]):
    X_design_3.append(X[:, i] ** 3)
    for j in range(i, X.shape[1]):
        for k in range(j, X.shape[1]):
            X_design_3.append(X[:, i] * X[:, j] * X[:, k])
X_design_3 = np.column_stack(X_design_3)
X_transpose_3 = X_design_3.T
I_3 = np.identity(X_design_3.shape[1])
beta_3 = np.linalg.inv(X_transpose_3 @ X_design_3 + lambda_reg_3 * I_3) @ X_transpose_3 @ y
y_pred_3 = X_design_3 @ beta_3
mse3 = np.mean((y - y_pred_3) ** 2)

print("Mean Squared Error:", mse3)

Mean Squared Error: 0.539742559729076


We also have the 4_degree polynomial regression as above

In [325]:
X_design_4 = [np.ones(X.shape[0])]
lambda_reg_4=1
for i in range(X.shape[1]):
    X_design_4.append(X[:, i])
for i in range(X.shape[1]):
    for j in range(i, X.shape[1]): 
        X_design_4.append(X[:, i] * X[:, j])
for i in range(X.shape[1]):
    X_design_4.append(X[:, i] ** 3)
    for j in range(i, X.shape[1]):
        for k in range(j, X.shape[1]):
            X_design_4.append(X[:, i] * X[:, j] * X[:, k])
for i in range(X.shape[1]):
    X_design_4.append(X[:, i] ** 4) 
    for j in range(i, X.shape[1]):
        for k in range(j, X.shape[1]):
            for l in range(k, X.shape[1]):
                X_design_4.append(X[:, i] * X[:, j] * X[:, k] * X[:, l])
X_design_4 = np.column_stack(X_design_4)
X_transpose_4 = X_design_4.T
I_4 = np.identity(X_design_4.shape[1])
beta_4 = np.linalg.inv(X_transpose_4 @ X_design_4 + lambda_reg_4 * I_4) @ X_transpose_4 @ y
y_pred_4 = X_design_4 @ beta_4
mse4 = np.mean((y - y_pred_4) ** 2)

print("Mean Squared Error:", mse4)

Mean Squared Error: 0.4476374030401085


From the MSE of all model below, we believe that with the complexity of higher degree model, the data can be fit more than ever, with the MSE decrease sharply from 0.73 to 0.44